Haskell technicalities.

* Set up a new project with Cabal

** building Haskell programs with modules

cabal init

edit cabal file
#+BEGIN_SRC haskell
-- Initial hello-haskell.cabal generated by cabal init.  For further 
-- documentation, see http://haskell.org/cabal/users-guide/

name:                hello-haskell
version:             0.1.0.0
synopsis:            Hello World App
-- description:
license:             BSD3
license-file:        LICENSE
author:              Ed Maphis
maintainer:          emaphis85@gmail.com
-- copyright:
category:            Text
build-type:          Simple
extra-source-files:  ChangeLog.md
cabal-version:       >=1.10

executable hello-haskell
  main-is:             Main.hs
  -- other-modules:
  -- other-extensions:
  build-depends:       base >=4.10 && <4.11
  hs-source-dirs:      src
  default-language:    Haskell2010
#+END_SRC

executable hello-haskell
  main-is:             Main.hs
  ghc-options:         -Wall -fwarn-tabs

Make a 'src' directory for source code

Make a file called Main.hs for the main Haskell program.

Initialize git.
 git init  (maybe create on github then git clone)
 git add . 
 git commit -m "Initial commit"

$ cabal sandbox init
$ cabal install --only-dependencies

$ cabal build

$ ./dist/build/hello-haskell/hello-haskell Hello from Haskell! $
-- or
$ cabal repl
 *Main> main
 Hello from Haskell!


** Using the REPL with a Cabal project
$ cabal repl

-- with an executable clause in .cabal
$ cabal repl hello-haskell


** Making our own modules

Modules always begin with a header

#+BEGIN_SRC haskell
module Morse ( Morse
              , charToMorse
              , morseToChar
              , stringToMorse
              , letterToMorse
              , morseToLetter
              ) where
#+END_SRC

module Hello where ...


** Refactoring into a library

#+BEGIN_SRC haskell

library
  exposed-modules:     Hello
  ghc-options:         -Wall
  hs-source-dirs:      src
  build-depends:       base >= 4.10 && <5
  default-language:    Haskell2010

executable hello-haskell
  main-is:             Main.hs
  -- other-modules:
  -- other-extensions:
  build-depends:       base >=4.10 && <4.11
                     , hello
  hs-source-dirs:      src
  ghc-options:         -Wall
  default-language:    Haskell2010
#+END_SRC

** Loading code from another project
#+BEGIN_SRC haskell
executable call-lib
  main-is:             Main.hs
  build-depends:       base >=4.10 && <4.11
                     , hello
  hs-source-dirs:      src
  default-language:    Haskell2010
#+END_SRC

now refer and call library
#+BEGIN_SRC haskell
module Main where

import Hello

main :: IO ()
main =
  sayHello "Hello from call-lib"
#+END_SRC

now create sandbox
$ cabal sandbox init

now add local dependency
$ cabal sandbox add-source ../hello-haskell
$ cabal install --only-dependencies


** project conventions

* Set up a new project with Stack

$ stack new helloworld new-template

$ stack setup  -- for a new GHC setup.

$ stack build

-- for now use lts-9.3

-- now run
:~/helloworld$ stack exec helloworld-exe

-- now test

$ stack test

app/Main.hs
src/Lib.hs
test/Spec.hs
helloworld.cabal
stack.yaml
Setup.hs


-- set a non stack project
$ stack build --only-dependencies
